# Generated by Django 2.1.7 on 2019-02-26 06:03
"""
# Generated by Django 2.1.7 on 2019-02-26 06:03
"""
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """
    # Generated by Django 2.1.7 on 2019-02-26 06:03
    """
    dependencies = [
        ('newsurvey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=200)),
                ('emp_username', models.CharField(max_length=100)),
                ('emp_password', models.CharField(max_length=100)),
                ('emp_designation', models.CharField(max_length=100)),
                ('emp_address', models.CharField(max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              to='newsurvey.Organization')),
            ],
            options={
                'verbose_name_plural': 'Employees',
            },
        ),
    ]
