# Generated by Django 2.1.7 on 2019-02-28 05:22
"""
# Generated by Django 2.1.7 on 2019-02-26 06:03
"""
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """
    # Generated by Django 2.1.7 on 2019-02-26 06:03
    """

    dependencies = [
        ('newsurvey', '0002_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='org_Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=200)),
                ('admin_username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('admin_email', models.CharField(max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              to='newsurvey.Organization')),
            ],
            options={
                'verbose_name_plural': 'org_Admin',
            },
        ),
        migrations.RemoveField(
            model_name='employee',
            name='company',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
