# Generated by Django 2.1.7 on 2019-03-07 05:00
"""
# Generated by Django 2.1.7 on 2019-03-07 05:00
"""
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    # Generated by Django 2.1.7 on 2019-03-07 05:00
    """

    dependencies = [
        ('newsurvey', '0005_question_survey_surveyemployee_surveyquestion_surveyresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
